### ISSUE TITLE
DATASET: After BUILD go to ROLES page.

### ISSUE THREAD

**Issue by gjwgit** [gjwgit/rattle#413] opened 2024-09-11 06:04 UTC
## Description

After loading the dataset proceed to the ROLES page. This is what I **always** do as a user, so probably good to do it by default.

## Why

So that we show a new user that a new page is generated and they should get insight from this new page. It helps to train the user into using the navigation. It is also the first thing I need to do as an experienced user - go to PAGE 1 - and so it is useful to make this easier for me.

**Comment by junhaow1** [comment] 2024-09-23 17:38
![Image](https://github.com/user-attachments/assets/31a1ffbb-05bc-4498-a40f-0f1e39b0696d)

**Comment by junhaow1** [comment] 2024-09-23 18:53
demo video : 
https://github.com/user-attachments/assets/66254b00-e801-4325-af29-18da6fb02377

**Comment by junhaow1** [comment] 2024-09-23 18:55
1. Provider for PageController: I created a pageControllerProvider using Riverpod’s StateProvider to manage the PageController. 

2. Access PageController in DatasetDisplay: In the DatasetDisplay widget, I use ref.watch(pageControllerProvider) to access the PageController and attach it to the PageView.

3. Update PageController in DatasetPopup: In the DatasetPopup widget, I use ref.read(pageControllerProvider) to get access to the PageController and move to the second page after the dataset is loaded.

**Comment by gjwgit** [comment] 2024-09-24 02:55
We can head toward using PageViewer() as a replacement for Page? Desirable functionality

- [x] Touchpad pan left and right
- [x] After the dataset is loaded go to the next page (ROLES).
- [x] Expose navigation buttons along the bottom with circles we can tap
- [x] Once tested for DATASET, for any FEATURE after the build button is tapped move to the next page
- [ ] When returning to the DATASET tab if a dataset is loaded then by default show the ROLES page SPLIT INTO A SEPARATE ISSE AND RAISE A PR.

**Comment by Lutra-Fs** [comment] 2024-09-24 07:28
Is this a duplicate of #202?

**Comment by gjwgit** [comment] 2024-09-24 11:15
Yes it is. Thanks for picking that up @Lutra-Fs. I have closed #202

**Comment by gjwgit** [comment] 2024-09-24 11:16
The current branch kev/413_page is great so far. Now to add the navigation. Then migrate to replace Page (with PageView).

**Comment by junhaow1** [comment] 2024-09-24 22:58
![Image](https://github.com/user-attachments/assets/0f6ad6db-9b12-445c-943c-010add48d626)

**Comment by junhaow1** [comment] 2024-09-27 00:06
https://github.com/gjwgit/rattleng/pull/483 PR created

**Comment by junhaow1** [comment] 2024-09-27 00:10
New issue created to fix integration tests: https://github.com/gjwgit/rattleng/issues/485

**Comment by gjwgit** [comment] 2024-09-29 20:15
AS per #483 this is failing for me at present. Moving back to in progress.

**Closed as completed** 2024-09-30 02:27 UTC
